# Generated by Django 4.2.1 on 2024-02-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InnImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inn_images')),
            ],
        ),
        migrations.CreateModel(
            name='InnModel',
            fields=[
                ('inn_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('date', models.DateField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
