# Generated by Django 4.2.1 on 2024-03-02 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crudinn', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='innmodel',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='innimagemodel',
            name='inn_image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudinn.innmodel'),
        ),
    ]
