# Generated by Django 4.2.1 on 2024-02-28 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crudinn', '0003_innmodel_anonymization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('chat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1_chatmodels', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2_chatmodels', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='ChatContentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.chatmodel')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='ApplyInnModel',
            fields=[
                ('apply_inn_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('info', models.CharField(blank=True, max_length=500)),
                ('phone_num', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=False)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_applyinnmodels', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_applyinnmodels', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('inn_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudinn.innmodel')),
            ],
        ),
    ]
