# Generated by Django 4.2.1 on 2024-03-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyInnModel',
            fields=[
                ('apply_inn_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('info', models.CharField(blank=True, max_length=500)),
                ('phone_num', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChatContentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('chat_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
