# Generated by Django 4.2.1 on 2024-03-02 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crudinn', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1_chatmodels', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2_chatmodels', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='chatcontentmodel',
            name='chat_content_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.chatmodel'),
        ),
        migrations.AddField(
            model_name='chatcontentmodel',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='applyinnmodel',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_applyinnmodels', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='applyinnmodel',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_applyinnmodels', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='applyinnmodel',
            name='inn_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudinn.innmodel'),
        ),
    ]
